### ISSUE TITLE
Small mistake in JSON file...

### ISSUE THREAD

**Issue by theothernt** [glouel/AerialCommunity#2]
On [line 37](https://github.com/AerialScreensaver/AerialCommunity/blob/master/entries.json#L37) there is a tiny mistake...

` "url-1080-H64"` should be ` "url-1080-H264"`

**Comment by glouel** [comment]
Oh wow ! 

My bad, that's been here a while, I'll fix it tonight ! Thanks a lot for the heads up @theothernt !

**Comment by theothernt** [comment]
I'm guessing no one uses H.264 these days, I only found the issue as I was testing on an old phone :)

(I'm hoping to add this feed to Aerial Views for Android TV, just waiting to hear back from Jetson Creative)

**Comment by glouel** [comment]
Finally fixed, thanks again for the report !
